# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout โค้ด
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 2. ตั้งค่า Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
      
      # 3. ติดตั้ง Dependencies (gh-pages ไม่จำเป็นแล้ว)
      - name: Install dependencies
        run: npm install
        
      # 4. รันคำสั่ง Build
      - name: Build project
        run: npm run build
        
      # 5. ตั้งค่า GitHub Pages Environment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 6. Upload โฟลเดอร์ Build ไปที่ GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # โฟลเดอร์ที่ Vite Build ออกมา
          
      # 7. Deploy ไปที่ GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
